name: NMT Check Bank

on:
  schedule:
    # Щосуботи о 09:00 Київ = 06:00 UTC
    - cron: '0 6 * * 6'
  workflow_dispatch:

jobs:
  check-bank:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Check bank
        run: python check_bank.py
